export const ALL_PERMISSIONS = [
  "catalog:read",
  "catalog:write",
  "inventory:read",
  "inventory:write",
  "sales:read",
  "sales:write",
  "purchasing:read",
  "purchasing:write",
  "approvals:read",
  "approvals:write",
  "finance:read",
  "finance:write",
  "manufacturing:read",
  "manufacturing:write",
  "hr:read",
  "hr:write",
  "auth:users:read",
  "auth:users:write",
  "auth:roles:read",
  "auth:roles:write",
  "auth:sessions:read",
  "auth:sessions:write",
  "tenant:read",
  "tenant:write",
  "dashboard:read",
  "audit:read",
  "notifications:read",
  "imports:read",
  "imports:write",
  "exports:read",
] as const;

export const ROLE_PRESETS: Record<string, string[]> = {
  admin: [...ALL_PERMISSIONS],
  manager: [
    "catalog:read",
    "inventory:read",
    "sales:read",
    "sales:write",
    "purchasing:read",
    "purchasing:write",
    "approvals:read",
    "approvals:write",
    "finance:read",
    "manufacturing:read",
    "hr:read",
    "dashboard:read",
    "audit:read",
    "notifications:read",
    "exports:read",
  ],
  accountant: [
    "finance:read",
    "finance:write",
    "dashboard:read",
    "audit:read",
    "notifications:read",
    "exports:read",
  ],
  support: [
    "catalog:read",
    "inventory:read",
    "sales:read",
    "sales:write",
    "notifications:read",
  ],
  employee: ["hr:read", "notifications:read"],
  user: ["dashboard:read", "notifications:read", "approvals:read", "catalog:read", "inventory:read", "sales:read", "purchasing:read"],
};

export const PLAN_LIMITS = {
  starter: { maxUsers: 10, maxProducts: 500, features: [] as string[] },
  pro: { maxUsers: 50, maxProducts: 5000, features: ["manufacturing", "api-keys"] as string[] },
  enterprise: {
    maxUsers: 500,
    maxProducts: 50000,
    features: ["manufacturing", "api-keys", "multi-currency"] as string[],
  },
} as const;