export const ALL_PERMISSIONS = [
  "companies:read",
  "companies:write",
  "companies:create",
  "companies:delete",
  "users:read",
  "users:write",
  "users:create",
  "users:delete",
  "roles:read",
  "roles:write",
  "roles:create",
  "roles:delete",
  "profile:read",
  "profile:write",
  "profile:create",
  "profile:delete",
  "hr:read",
  "hr:write",
  "hr:create",
  "hr:delete",
  "accountant:read",
  "accountant:write",
  "accountant:create",
  "accountant:delete",
  "manufacturing:read",
  "manufacturing:write",
  "manufacturing:create",
  "manufacturing:delete",
  "purchasing:read",
  "purchasing:write",
  "purchasing:create",
  "purchasing:delete",
  "inventory:read",
  "inventory:write",
  "inventory:create",
  "inventory:delete",
  "catalog:read",
  "catalog:write",
  "catalog:create",
  "catalog:delete",
  "sales:read",
  "sales:write",
  "sales:create",
  "sales:delete",
] as const;

export const ROLE_PRESETS: Record<string, string[]> = {
  admin: [...ALL_PERMISSIONS],
  manager: [
    "catalog:read",
    "catalog:write",
    "catalog:create",
    "inventory:read",
    "inventory:write",
    "inventory:create",
    "sales:read",
    "sales:write",
    "sales:create",
    "purchasing:read",
    "purchasing:write",
    "purchasing:create",
    "manufacturing:read",
    "manufacturing:write",
    "manufacturing:create",
    "hr:read",
    "hr:write",
    "hr:create",
    "accountant:read",
    "users:read",
    "roles:read",
    "companies:read",
    "profile:read",
    "profile:write",
  ],
  accountant: [
    "accountant:read",
    "accountant:write",
    "accountant:create",
    "accountant:delete",
    "users:read",
    "roles:read",
    "companies:read",
    "profile:read",
    "profile:write",
  ],
  support: [
    "catalog:read",
    "catalog:write",
    "catalog:create",
    "inventory:read",
    "sales:read",
    "sales:write",
    "sales:create",
    "purchasing:read",
    "hr:read",
    "profile:read",
    "profile:write",
  ],
  employee: ["hr:read", "profile:read", "profile:write"],
  user: [
    "catalog:read",
    "inventory:read",
    "sales:read",
    "purchasing:read",
    "hr:read",
    "profile:read",
    "profile:write",
  ],
};

export const PLAN_LIMITS = {
  starter: { maxUsers: 10, maxProducts: 500, features: [] as string[] },
  pro: { maxUsers: 50, maxProducts: 5000, features: ["manufacturing", "api-keys"] as string[] },
  enterprise: {
    maxUsers: 500,
    maxProducts: 50000,
    features: ["manufacturing", "api-keys", "multi-currency"] as string[],
  },
} as const;